# -*- coding: utf-8 -*-
import os

# 翻译映射
translations = {
    "agent-architecture-audit": "AI智能体和LLM应用的全面诊断",
    "agent-eval": "编码智能体的面对面比较",
    "agent-harness-construction": "设计优化AI智能体行动空间",
    "agentic-engineering": "作为智能体工程师运作",
    "agentic-os": "构建持久化多智能体操作系统",
    "agent-introspection-debugging": "结构化自我调试工作流",
    "agent-payment-x402": "为AI智能体添加x402支付执行",
    "agent-sort": "构建基于证据的ECC安装计划",
    "ai-first-engineering": "团队的AI优先工程运营模式",
    "autonomous-agent-harness": "将Claude Code转变为全自主智能体系统",
    "autonomous-loops": "自主循环的模式和架构",
    "context-budget": "审计Claude Code上下文窗口消耗",
    "continuous-agent-loop": "持续自主智能体循环模式",
    "continuous-learning": "已弃用，请使用continuous-learning-v2",
    "continuous-learning-v2": "基于本能的学习系统",
    "cost-aware-llm-pipeline": "LLM API使用的成本优化模式",
    "cost-tracking": "跟踪报告Claude Code代币使用情况",
    "council": "召开四人委员会进行决策",
    "cowork": "Claude主导规划执行",
    "deep-agents-memory": "深度智能体需要记忆时调用此技能",
    "deep-research": "多源深度研究",
    "enterprise-agent-ops": "运营长生命周期智能体工作负载",
    "error-handling": "健壮错误处理模式",
    "eval-harness": "Claude Code会话的正式评估框架",
    "foundation-models-on-device": "Apple设备端LLM的FoundationModels框架",
    "gan-style-harness": "GAN风格的生成器-评估器智能体框架",
    "iterative-retrieval": "逐步优化上下文检索的模式",
    "make-interfaces-feel-better": "应用具体的UI设计工程细节",
    "mle-workflow": "生产机器学习工程工作流",
    "parallel-deep-research": "仅在用户明确要求时使用",
    "plan-orchestrate": "读取计划文档并分解为步骤",
    "R2R": "从研究到报告的深度研究系统",
    "ralphinho-rfc-pipeline": "RFC驱动的多智能体DAG执行模式",
    "report-generator": "从模板生成PDF/HTML报告",
    "rules-distill": "扫描技能提取横切原则",
    "safety-guard": "防止破坏性操作的安全技能",
    "santa-method": "带收敛环的多智能体对抗验证",
    "search-first": "编码前研究工作流",
    "strategic-compact": "建议手动上下文压缩",
    "tdd-workflow": "编写新功能时使用此技能",
    "token-budget-advisor": "代币预算顾问",
    "verification-loop": "Claude Code会话的综合验证系统",
    "backend-patterns": "后端架构模式",
    "clickhouse-io": "ClickHouse数据库模式",
    "click-path-audit": "追踪每个用户界面按钮的完整状态变化",
    "dashboard-builder": "构建监控仪表板",
    "database-migrations": "数据库迁移最佳实践",
    "data-scraper-agent": "构建全自动AI数据采集智能体",
    "exa-search": "通过Exa MCP进行神经搜索",
    "excel-automation": "Excel自动化",
    "find-skills": "帮助用户发现和安装技能",
    "gget": "gget CLI和Python工作流用于快速基因组",
    "jpa-patterns": "JPA/Hibernate模式",
    "meeting-notes": "会议记录",
    "mysql-patterns": "MySQL和MariaDB模式",
    "postgres-patterns": "PostgreSQL数据库模式",
    "prisma-database-setup": "Prisma配置指南",
    "prisma-patterns": "Prisma ORM模式",
    "redis-patterns": "Redis数据结构模式",
    "supabase-postgres-best-practices": "Postgres性能优化",
    "xlsx": "处理电子表格文件时使用此技能",
    "ashare": "A股量化交易指南",
    "a-share-flow-analyzer": "A股机构/散户资金流智能分析",
    "a-stock": "A股全栈数据工具包",
    "a-stock-data": "A股全栈数据工具包",
    "china-stock-analyst": "A股短线分析助手",
    "recsys-pipeline-architect": "设计可组合推荐系统",
    "simonlin1212-a-stock-data": "A股全栈数据工具包",
    "stock-analysis": "股票分析",
    "stock-analyst": "股票技术分析专家",
    "viekai-analyse-skills": "上市公司综合财务分析系统",
    "android-clean-architecture": "Android清洁架构模式",
    "design-system": "生成或审计设计系统",
    "flutter-dart-code-review": "Flutter/Dart代码审查清单",
    "frontend-design-direction": "设置ECC特定的前端设计方向",
    "frontend-patterns": "前端开发模式",
    "frontend-slides": "创建精美的动画HTML演示",
    "hyperframes": "创建视频合成",
    "ios-icon-gen": "生成iOS应用图标",
    "liquid-glass-design": "iOS 26液态玻璃设计系统",
    "manim-video": "构建可复用的Manim解释器",
    "motion-advanced": "高级动画模式",
    "motion-foundations": "动画令牌、弹簧预设",
    "motion-patterns": "生产就绪的动画模式",
    "motion-ui": "生产就绪的UI动画系统",
    "nextjs-turbopack": "Next.js 16+和Turbopack",
    "nuxt4-patterns": "Nuxt 4应用模式",
    "ppt-master": "PPT大师",
    "pptx": "处理PowerPoint文件时使用此技能",
    "remotion-video-creation": "Remotion最佳实践",
    "ui-demo": "录制精美的UI演示视频",
    "ui-to-vue": "UI截图或设计导出",
    "videodb": "看、理解、行动于视频和音频",
    "video-editing": "AI辅助视频编辑工作流",
    "vite-patterns": "Vite构建工具模式",
    "article-writing": "撰写文章、指南、博客文章",
    "brand-voice": "构建源自真实内容的写作风格配置",
    "connections-optimizer": "重组用户的X和LinkedIn网络",
    "content-engine": "创建平台原生内容系统",
    "content-hash-cache-pattern": "缓存昂贵的文件处理结果",
    "content-strategy": "用户需要规划内容策略时",
    "crosspost": "多平台内容分发",
    "email-ops": "证据优先的邮箱分类",
    "fal-ai-media": "通过fal.ai MCP统一媒体生成",
    "gateguard": "阻止编辑/写入/Bash的事实门控",
    "messages-ops": "证据优先的实时消息工作流",
    "regex-vs-llm-structured-text": "选择正则表达式和LLM的决策框架",
    "repo-scan": "跨栈源代码资产审计",
    "seo": "审计、规划和实施SEO改进",
    "social-graph-ranker": "加权社交图谱排名",
    "visa-doc-translate": "翻译签证申请文件",
    "lead-get": "客户线索获取助手",
    "lead-hunter": "销售线索收集技能",
    "lead-intelligence": "AI原生线索智能和外联管道",
    "project-flow-ops": "跨GitHub和Linear运营执行流",
    "team-builder": "用于组合的交互式智能体选择器",
    "architecture-decision-records": "捕获架构决策",
    "company-financial-analysis": "综合财务分析系统",
    "experiments": "实验",
    "geo-content-optimizer": "当用户要求优化AI引用时",
    "healthcare-cdss-patterns": "临床决策支持系统",
    "healthcare-emr-patterns": "EMR/EHR开发模式",
    "healthcare-eval-harness": "患者安全评估工具",
    "healthcare-phi-compliance": "受保护健康信息",
    "hexagonal-architecture": "设计、实现和重构端口和适配器",
    "investor-materials": "创建和更新推介材料",
    "investor-outreach": "起草冷邮件、温暖介绍简介",
    "literature-review": "系统文献综述工作流",
    "market-research": "进行市场研究",
    "prd-development": "构建结构化PRD",
    "product-capability": "翻译PRD意图",
    "production-audit": "本地证据生产就绪审计",
    "production-scheduling": "生产调度",
    "product-lens": "验证为什么再构建",
    "pubmed-database": "直接PubMed和NCBI E-utilities搜索",
    "research-ops": "证据优先的当前状态研究工作流",
    "scholar-evaluation": "结构化学术工作评估",
    "uspto-database": "USPTO专利和商标数据工作流",
    "windows-desktop-e2e": "Windows原生桌面应用E2E测试",
    "api-connector-builder": "构建新的API连接器",
    "api-design": "REST API设计模式",
    "automation-audit-ops": "证据优先的自动化库存和重叠审计",
    "canary-watch": "监控和验证已部署的URL",
    "carrier-relationship-management": "承运商关系管理",
    "cisco-ios-patterns": "Cisco IOS和IOS-XE审查模式",
    "deployment-patterns": "部署工作流、CI/CD管道模式",
    "dmux-workflows": "使用dmux的多智能体编排",
    "docker-compose-orchestration": "Docker Compose容器编排",
    "docker-patterns": "Docker和Docker Compose模式",
    "ecc-tools-cost-audit": "证据优先的ECC工具消耗和计费审计",
    "energy-procurement": "能源采购",
    "finance-billing-ops": "证据优先的收入、定价、退款",
    "firecrawl-build-interact": "集成Firecrawl交互功能",
    "firecrawl-build-onboarding": "集成Firecrawl入门",
    "firecrawl-build-scrape": "集成Firecrawl抓取功能",
    "firecrawl-build-search": "集成Firecrawl搜索功能",
    "github-actions-docs": "用户询问如何编写时使用",
    "github-ops": "GitHub仓库操作",
    "git-workflow": "Git工作流模式",
    "google-workspace-ops": "跨Google Drive、文档、表格运营",
    "grafana-oss": "Grafana开源版",
    "helm-chart-scaffolding": "设计、组织和管理Helm图表",
    "homelab-network-readiness": "家庭实验室VLAN分段就绪清单",
    "homelab-network-setup": "实用家庭和实验室网络规划",
    "homelab-pihole-dns": "Pi-hole安装、封锁列表管理",
    "homelab-vlan-segmentation": "将家庭网络分段为VLAN",
    "homelab-wireguard-vpn": "WireGuard VPN服务器设置",
    "inventory-demand-planning": "库存需求规划",
    "jira-integration": "检索Jira工单时使用此技能",
    "logistics-exception-management": "物流异常管理",
    "mcp-server-patterns": "使用Node/TypeScript SDK构建MCP服务器",
    "n8n-cli": "使用n8n CLI管理工作流",
    "n8n-content-design": "n8n内容设计",
    "n8n-conventions": "n8n模式快速参考",
    "n8n-create-community-node-lint-rule": "n8n社区节点lint规则",
    "n8n-create-issue": "创建Linear工单或GitHub问题",
    "n8n-create-pr": "创建GitHub拉取请求",
    "n8n-create-skill": "n8n创建技能",
    "n8n-db-migrations": "编写n8n数据库迁移",
    "n8n-design-system": "设计系统样式指南",
    "n8n-linear-issue": "获取和分析Linear问题",
    "n8n-loom-transcript": "获取并显示Loom视频URL的完整转录",
    "n8n-node-add-oauth": "添加OAuth2凭证支持",
    "n8n-protect-endpoints": "应用n8n的RBAC范围装饰器到REST端点",
    "n8n-reproduce-bug": "从Linear工单复现bug",
    "n8n-spec-driven-development": "保持实现和规格同步",
    "nanoclaw-repl": "运营和扩展NanoClaw v2",
    "netmiko-ssh-automation": "安全的Python Netmiko模式",
    "network-bgp-diagnostics": "仅诊断BGP故障排除模式",
    "network-config-validation": "路由器和交换机配置部署前检查",
    "network-interface-health": "诊断接口错误、丢弃、CRC",
    "opensource-pipeline": "开源管道：分叉、清理和打包",
    "quality-nonconformance": "质量不合格",
    "returns-reverse-logistics": "退货和逆向物流",
    "terminal-ops": "证据优先的仓库执行工作流",
    "terraform-aws-modules": "AWS的Terraform模块创建",
    "uncloud": "管理Uncloud集群时使用",
    "unified-notifications-ops": "作为ECC原生工作流运营通知",
    "accessibility": "设计、实现和审计包容性数字产品",
    "angular-developer": "生成Angular代码并提供架构指导",
    "blender-motion-state-inspection": "检查Blender角色时使用此技能",
    "blueprint": "蓝图",
    "browser-automation": "浏览器自动化控制",
    "browser-qa": "自动化视觉测试",
    "bun-runtime": "Bun作为运行时、包管理器、捆绑器和测试运行器",
    "ck": "Claude Code的持久化每项目内存",
    "coding-standards": "跨项目编码约定基线",
    "compose-multiplatform-patterns": "Compose Multiplatform和Jetpack Compose模式",
    "configure-ecc": "Everything Claude Code的交互式安装程序",
    "cpp-coding-standards": "C++编码标准",
    "cpp-testing": "仅在编写/更新/修复C++测试时使用",
    "csharp-testing": "C#和.NET测试模式",
    "dart-flutter-patterns": "生产就绪的Dart和Flutter模式",
    "django-celery": "Django + Celery异步任务模式",
    "django-patterns": "Django架构模式",
    "django-security": "Django安全最佳实践",
    "django-tdd": "Django测试策略",
    "django-verification": "Django项目验证循环",
    "dotnet-patterns": "惯用C#和.NET模式",
    "e2e-testing": "Playwright E2E测试模式",
    "fastapi-patterns": "FastAPI异步API模式",
    "fastapi-python": "FastAPI Python开发专家",
    "flox-environments": "创建可复用的跨平台开发环境",
    "fsharp-testing": "F#测试模式",
    "golang-patterns": "惯用Go模式",
    "golang-testing": "Go测试模式",
    "hermes-imports": "转换本地Hermes操作符工作流",
    "hookify-rules": "当用户询问时使用此技能",
    "java-coding-standards": "Java编码标准",
    "kotlin-coroutines-flows": "Kotlin协程和Flow模式",
    "kotlin-exposed-patterns": "JetBrains Exposed ORM模式",
    "kotlin-ktor-patterns": "Ktor服务器模式",
    "kotlin-patterns": "惯用Kotlin模式",
    "kotlin-testing": "Kotlin测试模式",
    "laravel-patterns": "Laravel架构模式",
    "laravel-plugin-discovery": "发现和评估Laravel包",
    "laravel-security": "Laravel安全最佳实践",
    "laravel-tdd": "Laravel测试驱动开发",
    "laravel-verification": "Laravel项目验证循环",
    "nestjs-patterns": "NestJS架构模式",
    "nodejs-keccak256": "防止JavaScript中的以太坊哈希错误",
    "openclaw-persona-forge": "为OpenClaw AI Agent锻造完整的龙虾灵魂方案",
    "perl-patterns": "现代Perl 5.36+惯用语",
    "perl-security": "全面的Perl安全",
    "perl-testing": "Perl测试模式",
    "python-patterns": "Pythonic惯用语、PEP 8标准",
    "python-testing": "Python测试策略",
    "pytorch-patterns": "PyTorch深度学习模式",
    "quarkus-patterns": "Quarkus 3.x LTS架构模式",
    "quarkus-security": "Quarkus安全最佳实践",
    "quarkus-tdd": "Quarkus测试驱动开发",
    "quarkus-verification": "Quarkus项目验证循环",
    "rust-patterns": "惯用Rust模式",
    "rust-testing": "Rust测试模式",
    "springboot-patterns": "Spring Boot架构模式",
    "springboot-security": "Spring安全最佳实践",
    "springboot-tdd": "Spring Boot测试驱动开发",
    "springboot-verification": "Spring Boot项目验证循环",
    "swift-actor-persistence": "Swift中的线程安全数据持久化",
    "swift-concurrency-6-2": "Swift 6.2可接近并发",
    "swift-protocol-di-testing": "基于协议的依赖注入用于测试",
    "swiftui-patterns": "SwiftUI架构模式",
    "tinystruct-patterns": "使用tinystruct开发的专家指导",
    "x-api": "X/Twitter API集成用于发布推文",
    "codebase-onboarding": "分析不熟悉的代码库",
    "code-tour": "创建CodeTour文件",
    "documentation-lookup": "使用最新的库和框架文档",
    "knowledge-ops": "知识库管理、摄取、同步",
    "markitdown": "将文件转换为Markdown",
    "notion-research-documentation": "跨Notion研究和综合",
    "nutrient-document-processing": "处理、转换、OCR、提取、编辑、签名",
    "pdf": "用户需要处理PDF时使用此技能",
    "customer-billing-ops": "运营客户计费工作流",
    "customs-trade-compliance": "海关贸易合规",
    "defi-amm-security": "Solidity AMM合约安全检查清单",
    "evm-token-decimals": "防止静默小数不匹配错误",
    "hipaa-compliance": "医疗保健的HIPAA特定入口点",
    "llm-trading-agent-security": "自主交易智能体的安全模式",
    "prompt-guard": "Meta的8600万提示注入和越狱数据集守护",
    "prompt-optimizer": "提示优化器",
    "security-bounty-hunter": "搜寻可利用的、值得赏金的安全漏洞",
    "security-review": "添加身份验证时使用此技能",
    "security-scan": "扫描Claude Code配置",
    "skill-comply": "可视化技能、规则和智能体",
    "skill-scout": "搜索现有的本地、市场、GitHub",
    "skill-stocktake": "审计Claude技能和命令时使用",
    "vulnerability-scanning": "依赖项的自动安全扫描",
    "workspace-surface-audit": "审计活动仓库、MCP服务器、插件",
    "ai-regression-testing": "AI辅助的回归测试策略",
    "algorithmic-art": "使用p5.js创建算法艺术",
    "benchmark": "测量性能基准时使用此技能",
    "brand-guidelines": "应用Anthropic的官方品牌颜色和排版",
    "canvas-design": "创建精美的.png和.pdf视觉艺术",
    "claude-api": "构建、调试和优化Claude API",
    "claude-devfleet": "编排多智能体编码任务",
    "doc-coauthoring": "引导用户完成结构化工作流",
    "docx": "用户需要处理Word文档时使用此技能",
    "ecc-guide": "引导用户了解ECC当前的智能体",
    "everything-claude-code": "开发约定和模式",
    "everything-claude-code-conventions": "开发约定和模式",
    "frontend-design": "创建独特的生产级前端",
    "internal-comms": "帮助我写作的各种资源",
    "mcp-builder": "创建高质量MCP的指南",
    "plankton-code-quality": "写入时代码质量执行",
    "skill-creator": "创建新技能、修改和改进现有技能",
    "slack-gif-creator": "用于创建动画GIF的知识和工具",
    "template": "替换为技能描述",
    "theme-factory": "使用主题为 artifacts 造型",
    "webapp-testing": "用于交互和测试本地Web应用的工具包",
    "web-artifacts-builder": "用于创建精细的多层Web体验的工具套件",
}

# 读取原始数据
skills = []
with open(os.path.join(os.path.dirname(__file__), 'all_skills.txt'), 'r', encoding='utf-8') as f:
    for line in f:
        parts = line.strip().split('|')
        if len(parts) >= 4:
            name, category, desc, date = parts[0], parts[1], parts[2], parts[3]
            cn_desc = translations.get(name, desc[:60] + '...' if len(desc) > 60 else desc)
            skills.append({
                'name': name,
                'category': category,
                'description': cn_desc,
                'date': date
            })

# 按分类和名称排序
cats_order = ['01-AI工作流', '02-数据分析', '03-A股量化', '04-VibeCoding', '05-内容创作', '06-职场效率', '07-研究调研', '08-基础设施', '09-开发框架', '10-知识库', '11-安全防护', '12-Claude原厂']
skills.sort(key=lambda x: (cats_order.index(x['category']) if x['category'] in cats_order else 99, x['name']))

# 输出表格
print("序号 | 名称                                   | 分类          | 技能描述                                          | 安装时间")
print("-" * 130)

for i, s in enumerate(skills, 1):
    name = s['name'][:38] if len(s['name']) > 38 else s['name']
    cat = s['category'][:13] if len(s['category']) > 13 else s['category']
    desc = s['description'][:48] if len(s['description']) > 48 else s['description']
    date = s['date'][:15] if len(s['date']) > 15 else s['date']
    print(f"{i:3} | {name:<38} | {cat:<12} | {desc:<48} | {date}")

print("-" * 130)
print(f"总计: {len(skills)} 个技能")