<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>LicenseTest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DormManage.Shared\DormManage.Shared.csproj" />
    <ProjectReference Include="..\..\DormManage.TrayApp\DormManage.TrayApp.csproj" />
  </ItemGroup>
</Project>